name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # These values can be published.
      # Actual authentication for data is done with Firebase Auth.
      REACT_APP_API_KEY: AIzaSyDgkUWXFV25qNkSICMSUMavPo648VTwA8k
      REACT_APP_AUTH_DOMAIN: room-system-firebase.firebaseapp.com
      REACT_APP_DATABASE_URL: https://room-system-firebase.firebaseio.com
      REACT_APP_PROJECT_ID: room-system-firebase
      REACT_APP_STORAGE_BUCKET: room-system-firebase.appspot.com
      REACT_APP_MESSAGING_SENDER_ID: 918701774845
      REACT_APP_APP_ID: 1:918701774845:web:460a0cc64b03748d516b94

    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master

      - name: Clone
        run: git clone https://github.com/aoirint/room-system-frontend.git .

      - name: Build Docker Image
        run: docker build . -t aoirint/room-system-frontend

      - name: Build Node.js Website
        run: |
          docker run --rm \
            -e REACT_APP_API_KEY \
            -e REACT_APP_AUTH_DOMAIN \
            -e REACT_APP_DATABASE_URL \
            -e REACT_APP_PROJECT_ID \
            -e REACT_APP_STORAGE_BUCKET \
            -e REACT_APP_MESSAGING_SENDER_ID \
            -e REACT_APP_APP_ID \
            -v "$PWD:/code" \
            aoirint/room-system-frontend \
            npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
